### ISSUE TITLE
BackupFileStream finalizer throws NullReferenceException, after the constructor throws an exception.

### ISSUE THREAD

**Issue by diontools** [alphaleonis/AlphaFS#175]
At the BackupFileStream, the finalizer throws NullReferenceException, after the constructor throws an exception.
## Sample code

``` csharp
            try
            {
                using (var stream =
                    new Alphaleonis.Win32.Filesystem.BackupFileStream(
                        @"C:\NotExistsDir\example.txt",
                        System.IO.FileMode.Open,
                        System.Security.AccessControl.FileSystemRights.Read,
                        System.IO.FileShare.Read,
                        Alphaleonis.Win32.Filesystem.ExtendedFileAttributes.BackupSemantics))
                {
                }
            }
            catch
            {
                // DirectoryNotFoundException
            }

            // throw NullReferenceException by BackupFileStream finalizer
```
## StackTrace

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Alphaleonis.Win32.Filesystem.BackupFileStream.Dispose(Boolean disposing)
   at Alphaleonis.Win32.Filesystem.BackupFileStream.Finalize()
```

Thank you for reading.
diontools

**Comment by Yomodo** [comment]
Thank you!
