### ISSUE TITLE
EnumerateFileSystemInfos igoring ContinueOnException for Illegal Character

### ISSUE THREAD

**Issue by milos12345** [alphaleonis/AlphaFS#315]
Is this error something that needs in the AlphaFS or is it something I should be able to fix in my code. It ContinueOnException does not seem to work in this case:

```
System.ArgumentException: Illegal characters: [
] in path.
Parameter name: E:\.HFS+ Private Directory Data

   at Alphaleonis.Win32.Filesystem.Path.CheckInvalidPathChars(String path, Boolean checkAdditional, Boolean allowEmpty) in e:\AlphaFS\AlphaFS\Filesystem\Path Class\Path.ValidationAndChecks.cs:line 199
   at Alphaleonis.Win32.Filesystem.Path.GetFileName(String path, Boolean checkInvalidPathChars) in e:\AlphaFS\AlphaFS\Filesystem\Path Class\Path.GetComponents.cs:line 231
   at Rapidrive.FFControl.<List>b__19(FileSystemInfo p) in FFControl.xaml.cs:line 807
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.<SkipIterator>d__30`1.MoveNext()
   at System.Reactive.Linq.ObservableImpl.ToObservable`1._.Loop(IEnumerator`1 enumerator, ICancelable cancel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.Stubs.<.cctor>b__1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Finally`1._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.DelaySubscription`1._.OnError(Exception error)
   at System.Reactive.Concurrency.ObserveOn`1.ObserveOnSink.OnErrorPosted(Object error)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
-CR symbol I guess? I got similar reports from several users, mac formatted drives and browsing content copied from Android phone

The line in my code that causes the crash is
` IObservable<IList<FileSystemInfo>> bufferedFSI=Observable.Interval(TimeSpan.FromSeconds(.1), Scheduler.Default).StartWith(0).Zip(dir.EnumerateFileSystemInfos(filter, DirectoryEnumerationOptions.ContinueOnException).OrderByDescending(p => p.LastWriteTime).ToObservable(NewThreadScheduler.Default)
                                .Buffer(1000), (a, b) => b).ObserveOn(syncContext).DelaySubscription(new TimeSpan(0, 0, 0, 0, 1)).Finally(OnFinally);`

**Comment by Yomodo** [comment]
The mentioned path: `.HFS+ Private Directory Data` seems ok (I can create a folder by that name locally).

`ContinueOnException` only works with enumerating methods.

If you have access to the `Path.GetFileName()` call (2nd line of stack trace) you can call the method with `checkInvalidPathChars = false` to see if it makes a difference.

**Comment by milos12345** [comment]
I think that path has \r in there and I was unable to make a folder like that (see new line between [ and ]
Actually it looks like the part where it crashes is:
dir.EnumerateFileSystemInfos(filter, DirectoryEnumerationOptions.ContinueOnException)
I will try your fix for the next update and see it if still get the crash reports there. Thanks!

**Comment by Yomodo** [comment]
No user feedback received.
